config/routes.rb
Rails.application.routes.draw do
  resources :yourplans
  resources :static_workloads
  resources :schedules
  resources :average_grades
  resources :tracks
  resources :professors
  resources :courses
  devise_for :students

  root 'students#index'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/average_grade.rb
class AverageGrade < ApplicationRecord
end

app/controllers/average_grades_controller.rb
class AverageGradesController < ApplicationController
  before_action :set_average_grade, only: [:show, :edit, :update, :destroy]

  # GET /average_grades
  # GET /average_grades.json
  def index
    @average_grades = AverageGrade.all
  end

  # GET /average_grades/1
  # GET /average_grades/1.json
  def show
  end

  # GET /average_grades/new
  def new
    @average_grade = AverageGrade.new
  end

  # GET /average_grades/1/edit
  def edit
  end

  # POST /average_grades
  # POST /average_grades.json
  def create
    @average_grade = AverageGrade.new(average_grade_params)

    respond_to do |format|
      if @average_grade.save
        format.html { redirect_to @average_grade, notice: 'Average grade was successfully created.' }
        format.json { render :show, status: :created, location: @average_grade }
      else
        format.html { render :new }
        format.json { render json: @average_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /average_grades/1
  # PATCH/PUT /average_grades/1.json
  def update
    respond_to do |format|
      if @average_grade.update(average_grade_params)
        format.html { redirect_to @average_grade, notice: 'Average grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @average_grade }
      else
        format.html { render :edit }
        format.json { render json: @average_grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /average_grades/1
  # DELETE /average_grades/1.json
  def destroy
    @average_grade.destroy
    respond_to do |format|
      format.html { redirect_to average_grades_url, notice: 'Average grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_average_grade
      @average_grade = AverageGrade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def average_grade_params
      params.require(:average_grade).permit(:A, :B, :C, :D, :Other)
    end
end

app/helpers/average_grades_helper.rb
module AverageGradesHelper
end

app/views/average_grades/_form.html.erb
<%= form_with(model: average_grade, local: true) do |form| %>
  <% if average_grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(average_grade.errors.count, "error") %> prohibited this average_grade from being saved:</h2>

      <ul>
      <% average_grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :A %>
    <%= form.number_field :A, id: :average_grade_A %>
  </div>

  <div class="field">
    <%= form.label :B %>
    <%= form.number_field :B, id: :average_grade_B %>
  </div>

  <div class="field">
    <%= form.label :C %>
    <%= form.number_field :C, id: :average_grade_C %>
  </div>

  <div class="field">
    <%= form.label :D %>
    <%= form.number_field :D, id: :average_grade_D %>
  </div>

  <div class="field">
    <%= form.label :Other %>
    <%= form.number_field :Other, id: :average_grade_Other %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/average_grades/edit.html.erb
<h1>Editing Average Grade</h1>

<%= render 'form', average_grade: @average_grade %>

<%= link_to 'Show', @average_grade %> |
<%= link_to 'Back', average_grades_path %>

app/views/average_grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Average Grades</h1>

<table>
  <thead>
    <tr>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
      <th>Other</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @average_grades.each do |average_grade| %>
      <tr>
        <td><%= average_grade.A %></td>
        <td><%= average_grade.B %></td>
        <td><%= average_grade.C %></td>
        <td><%= average_grade.D %></td>
        <td><%= average_grade.Other %></td>
        <td><%= link_to 'Show', average_grade %></td>
        <td><%= link_to 'Edit', edit_average_grade_path(average_grade) %></td>
        <td><%= link_to 'Destroy', average_grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Average Grade', new_average_grade_path %>

app/views/average_grades/new.html.erb
<h1>New Average Grade</h1>

<%= render 'form', average_grade: @average_grade %>

<%= link_to 'Back', average_grades_path %>

app/views/average_grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A:</strong>
  <%= @average_grade.A %>
</p>

<p>
  <strong>B:</strong>
  <%= @average_grade.B %>
</p>

<p>
  <strong>C:</strong>
  <%= @average_grade.C %>
</p>

<p>
  <strong>D:</strong>
  <%= @average_grade.D %>
</p>

<p>
  <strong>Other:</strong>
  <%= @average_grade.Other %>
</p>

<%= link_to 'Edit', edit_average_grade_path(@average_grade) %> |
<%= link_to 'Back', average_grades_path %>