config/routes.rb
Rails.application.routes.draw do
  resources :yourplans
  resources :static_workloads
  resources :schedules
  resources :average_grades
  resources :tracks
  resources :professors
  resources :courses
  devise_for :students

  root 'students#index'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/yourplan.rb
class Yourplan < ApplicationRecord
  belongs_to :student
end

app/controllers/yourplans_controller.rb
class YourplansController < ApplicationController
  before_action :set_yourplan, only: [:show, :edit, :update, :destroy]

  # GET /yourplans
  # GET /yourplans.json
  def index
    @yourplans = Yourplan.where(student_id: current_student.id)
  end

  # GET /yourplans/1
  # GET /yourplans/1.json
  def show
  end

  # GET /yourplans/new
  def new
    @yourplan = Yourplan.new
  end

  # GET /yourplans/1/edit
  def edit
  end

  # POST /yourplans
  # POST /yourplans.json
  def create
    @yourplan = Yourplan.new(yourplan_params)
    respond_to do |format|
      if Yourplan.exists?(student_id: current_student.id, courses: @yourplan.courses)
        format.html { redirect_to root_path, notice: 'Course already exists in your plan.'  }
        format.json { render json: @yourplan.errors, status: :unprocessable_entity }
      elsif @yourplan.save
        format.html { redirect_to root_path, notice: 'Course was successfully added to your plan.' }
        format.json { render :show, status: :created, location: @yourplan }
      else
        format.html { redirect_to root_path }
        format.json { render json: @yourplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yourplans/1
  # PATCH/PUT /yourplans/1.json
  def update
    respond_to do |format|
      if @yourplan.update(yourplan_params)
        format.html { redirect_to @yourplan, notice: 'Yourplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @yourplan }
      else
        format.html { render :edit }
        format.json { render json: @yourplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yourplans/1
  # DELETE /yourplans/1.json
  def destroy
    @yourplan.destroy
    respond_to do |format|
      format.html { redirect_to yourplans_url, notice: 'Yourplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yourplan
      @yourplan = Yourplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yourplan_params
      params.require(:yourplan).permit(:student_id, :courses, :schedule_id)
    end
end

app/helpers/yourplans_helper.rb
module YourplansHelper
end

app/views/yourplans/_form.html.erb
<%= form_with(model: yourplan, local: true) do |form| %>
  <% if yourplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(yourplan.errors.count, "error") %> prohibited this yourplan from being saved:</h2>

      <ul>
      <% yourplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.text_field :student_id, id: :yourplan_student_id %>
  </div>

  <div class="field">
    <%= form.label :courses %>
    <%= form.text_field :courses, id: :yourplan_courses %>
  </div>

  <div class="field">
    <%= form.label :schedule_id %>
    <%= form.number_field :schedule_id, id: :yourplan_schedule_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/yourplans/edit.html.erb
<h1>Editing Yourplan</h1>

<%= render 'form', yourplan: @yourplan %>

<%= link_to 'Show', @yourplan %> |
<%= link_to 'Back', yourplans_path %>

app/views/yourplans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>MyPLan</h1>
<!-- Latest compiled and minified Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<% if student_signed_in? %>
    <% if @yourplans.blank? %>
        <p id="notice">No plan found, please add  <%= link_to('courses',root_path) %> to your plan.</p>
    <% else %>
    <br>
    <div class="panel-group" id="accordion">
      <% @yourplans.each do |yourplan| %>
          <% items = Schedule.select('id,semester,day,time').group('id').where(:id => yourplan.schedule_id) %>
          <% items.each do |schedule| %>
              <% courses = Course.select('id,code,course_name,syllabus_id,description,prerequisites,core').group('id').where(:id => yourplan.courses) %>
              <% courses.each do |course| %>
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h4 class="panel-title">
                        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne<%= course.syllabus_id %>">
                          CSC <%= course.code %> - <%= course.course_name %>
                        </a>
                        <% if course.core %>
                            <%= image_tag("red-flag-md.png", size: "10x10", :alt => "Core course", title: "Core course") %>
                        <% end %>
                        <i><span style="float: right;padding-right: 18px;"> <%= schedule.semester %>: <%= schedule.day %>, <%= schedule.time %>
                          </span></i>
                      </h4>
                    </div>
                    <div id="collapseOne<%= course.syllabus_id %>" class="panel-collapse collapse">
                      <div class="panel-body">
                        <p style="text-align:justify"><%= course.description %></p>
                        <i>Prerequisites: <%= course.prerequisites %> <br></i>
                        <i><br>
                          <%= schedule.semester %>: <%= schedule.day %>, <%= schedule.time %>
                          <%= button_to 'Remove', yourplan, method: :delete, data: { confirm: 'Are you sure?' } %>

                        </i><br>
                        <%= link_to('Course syllabus', "syllabus/#{course.code}.pdf", download: "#{course.course_name}") %>
                        <br>
                        <%= link_to('PalTalk', "forum/csc-#{course.code}", target: :_blank) %>
                      </div>
                    </div>
                  </div>
              <% end %>
          <% end %>
      <% end %>
    </div>
        <% end %>
<% end %>
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

app/views/yourplans/new.html.erb
<h1>New Yourplan</h1>

<%= render 'form', yourplan: @yourplan %>

<%= link_to 'Back', yourplans_path %>

app/views/yourplans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @yourplan.student %>
</p>

<p>
  <strong>Courses:</strong>
  <%= @yourplan.courses %>
</p>

<p>
  <strong>Schedule:</strong>
  <%= @yourplan.schedule_id %>
</p>

<%= link_to 'Edit', edit_yourplan_path(@yourplan) %> |
<%= link_to 'Back', yourplans_path %>