config/routes.rb
Rails.application.routes.draw do
  resources :yourplans
  resources :static_workloads
  resources :schedules
  resources :average_grades
  resources :tracks
  resources :professors
  resources :courses
  devise_for :students

  root 'students#index'
  mount Thredded::Engine => '/forum'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    if params[:q].present?
      clear_boolean(params[:q], :core_true)
      clear_boolean(params[:q], :schedules_project_true)
      clear_boolean(params[:q], :schedules_fieldwork_true)
      clear_select(params[:q], :schedules_semester_eq)
    end
    @q = Course.includes(:schedules).ransack(params[:q])
    print(@q)
    @courses = @q.result(distinct: true)
                   .includes(:schedules)
                   .joins(:schedules)
                   .order('courses.code')
                   .page(params[:page])
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:code, :syllabus_id, :prerequisites, :course_name, :core, :channel_id)
    end

    def clear_boolean(q, condition)
      q.delete(condition) if q[condition] == "0"
    end

  def clear_select(q, condition)
    q.delete(condition) if q[condition] == "Any"
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_courseList.html.erb
<!-- Latest compiled and minified Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
<% if student_signed_in? %>
<br>
<div class="panel-group" id="accordion">
  <% @courses.each do |course| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne<%= course.syllabus_id %>">
              CSC <%= course.code %> - <%= course.course_name %>
            </a>
            <% if course.core %>
                <%= image_tag("red-flag-md.png", size: "10x10", :alt => "Core course", title: "Core course") %>
            <% end %>
          </h4>
        </div>
        <div id="collapseOne<%= course.syllabus_id %>" class="panel-collapse collapse
          <% if course.syllabus_id == 1 %>
               in
          <% end %>">
          <div class="panel-body">
            <p style="text-align:justify"><%= course.description %></p>
            <i>Prerequisites: <%= course.prerequisites %> <br></i>
            <i><br><table id="search-criteria">
              <% items = Schedule.select('id,semester,day,time').group('id').where(:course_id => course.syllabus_id) %>
              <% items.each do |schedule| %>
                  <tr>
                    <td><%= schedule.semester %>: <%= schedule.day %>, <%= schedule.time %> &nbsp; &nbsp; &nbsp;</td>
                    <td><%= button_to "Add to My Plan", {:controller => :yourplans, :action => 'create',
                                                         :yourplan => {:student_id => current_student.id, :courses => course.syllabus_id, :schedule_id => schedule.id}}, :method => :post %></td>
                  </tr>
              <% end %>
            </table></i><br>
            <%= link_to('Course syllabus', "syllabus/#{course.code}.pdf", download: "#{course.course_name}") %>
            <br>
            <%= link_to('PalTalk', "forum/csc-#{course.code}", target: :_blank) %>
          </div>
        </div>
      </div>
  <% end %>
</div>
<% end %>
<!-- Latest compiled and minified JavaScript -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code, id: :course_code %>
  </div>

  <div class="field">
    <%= form.label :syllabus_id %>
    <%= form.text_field :syllabus_id, id: :course_syllabus_id %>
  </div>

  <div class="field">
    <%= form.label :prerequisites %>
    <%= form.text_field :prerequisites, id: :course_prerequisites %>
  </div>

  <div class="field">
    <%= form.label :course_name %>
    <%= form.text_field :course_name, id: :course_course_name %>
  </div>

  <div class="field">
    <%= form.label :core %>
    <%= form.check_box :core, id: :course_core %>
  </div>

  <div class="field">
    <%= form.label :channel_id %>
    <%= form.text_field :channel_id, id: :course_channel_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/_search.html.erb
<br>
<br>
<%= search_form_for(@q, html: {class: :'form-inline'}) do |f| %>
    <h3> Choose Search Criteria </h3>
    <table id="search-criteria">
      <tr>
        <td><%= f.label :course_name_or_code_cont, "Keywords" %></td>
        <td> <%= f.search_field :course_name_or_code_cont, class: 'form-control' %></td></t>
      </tr>
      <tr>
        <td><%= f.label :course_name_cont, "Course" %></td>
        <td><%= f.search_field :course_name_cont, class: 'form-control' %></td>
      </tr>
      <tr>
        <td><%= f.label :schedules_semester_eq, "Semester" %></td>
        <td><%= f.select(:schedules_semester_eq, ['Any','Fall','Spring'], {}, {class: 'form-control'}) %></td>
      </tr>
    </table>

    <div class="form-group">
      <%= f.check_box :core_true, class: 'form-control' %>
      <%= f.label :core_true, "core" %>
    </div>

    <div class="form-group">
      <%= f.check_box :schedules_project_true, class: 'form-control' %>
      <%= f.label :schedules_project_true, "project" %>
    </div>

    <div class="form-group">
      <%= f.check_box :schedules_fieldwork_true, class: 'form-control' %>
      <%= f.label :schedules_fieldwork_true, "fieldwork" %>
    </div>
    <br>
    <%= f.submit "Search", class: 'btn btn-primary' %>

<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<% content_for :top_content do %>
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to WolfPal!</h1>
        <p>Register to get started.</p>
        <p>
          <%= link_to 'Register', new_student_registration_path, class: 'btn btn-primary btn-lg' %>
        </p>
      </div>
    </div>
<% end %>

<% content_for :left_content do %>
    <%= render 'jsBot/index' %>
    <h2>List of Computer Science courses</h2>
    <%= render 'courseList' %>
<% end %>


<% content_for :right_content do %>
    <%= render "courses/search" %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Syllabus:</strong>
  <%= @course.syllabus_id %>
</p>

<p>
  <strong>Prerequisites:</strong>
  <%= @course.prerequisites %>
</p>

<p>
  <strong>Course name:</strong>
  <%= @course.course_name %>
</p>

<p>
  <strong>Core:</strong>
  <%= @course.core %>
</p>

<p>
  <strong>Channel:</strong>
  <%= @course.channel_id %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>